/**
 * The SUPARFLYYART "S" mark, traced from the master artwork as a single
 * closed polygon. Keeping it as path data (rather than a PNG) means it stays
 * razor-sharp at any size and can be drawn by Canvas, SVG, or Three.js alike.
 *
 * Generated by scripts/trace-logo.py — re-run that script instead of editing by hand.
 */
export const S_GLYPH = {
  width: 623,
  height: 713,
  path: "M622,0 495,127 419,52 310,52 172,189 174,356 272,356 338,293 410,293 456,338 456,464 351,570 280,570 224,514 223,428 0,651 0,712 181,531 265,613 367,613 498,483 499,322 428,251 322,250 250,319 217,320 215,207 323,99 405,98 459,152 459,224 622,61Z",
} as const;

/** Width ÷ height of the mark — used to size glyph cells without distortion. */
export const S_GLYPH_ASPECT = S_GLYPH.width / S_GLYPH.height;
