"""
trace-logo.py — turn the SUPARFLYYART logo PNG into vector data for the site.

Reads a black-on-white logo image, traces its outline, simplifies it down to
its corners, and writes:

  public/s-mark.svg          the mark as a standalone SVG
  src/lib/brand/sGlyph.ts    the path data the S-rain (and later 3D) uses

Usage (from the project root):

  pip install opencv-python numpy
  python scripts/trace-logo.py assets/logo.png

Options:
  --tolerance 2.5   max distance (px) the simplified outline may stray from the
                    original edge. Lower = more points / closer fit.
  --threshold 128   brightness cut-off between "logo" and "background" (0–255).
  --dry-run         print the result without writing any files.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import cv2
    import numpy as np
except ImportError:
    sys.exit("Missing packages. Run:  pip install opencv-python numpy")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SVG_OUT = PROJECT_ROOT / "public" / "s-mark.svg"
TS_OUT = PROJECT_ROOT / "src" / "lib" / "brand" / "sGlyph.ts"

MIN_SHAPE_AREA = 200  # px² — anything smaller is treated as a speck of noise


def trace(image_path: Path, threshold: int, tolerance: float) -> tuple[str, int, int, int]:
    """Return (svg_path_data, width, height, corner_count) for the logo."""
    image = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
    if image is None:
        sys.exit(f"Could not read image: {image_path}")

    # Flatten transparency onto white so transparent PNGs work too.
    if image.ndim == 3 and image.shape[2] == 4:
        alpha = image[:, :, 3:4].astype(np.float32) / 255.0
        rgb = image[:, :, :3].astype(np.float32)
        image = (rgb * alpha + 255.0 * (1.0 - alpha)).astype(np.uint8)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image

    # Dark pixels become the shape (white), light pixels the background (black).
    _, mask = cv2.threshold(gray, threshold, 255, cv2.THRESH_BINARY_INV)

    # RETR_CCOMP keeps holes too, so logos with enclosed counters still trace.
    contours, _ = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
    contours = [c for c in contours if cv2.contourArea(c) >= MIN_SHAPE_AREA]
    if not contours:
        sys.exit("No shape found — is the logo dark on a light background?")

    # Crop to the logo itself so coordinates start at 0,0.
    x, y, w, h = cv2.boundingRect(np.vstack(contours))

    parts: list[str] = []
    corners = 0
    for contour in contours:
        # Douglas–Peucker: drop points while staying within `tolerance` px.
        points = cv2.approxPolyDP(contour, tolerance, True).reshape(-1, 2)
        corners += len(points)
        parts.append("M" + " ".join(f"{px - x},{py - y}" for px, py in points) + "Z")

    return "".join(parts), w, h, corners


def write_svg(path_data: str, width: int, height: int) -> None:
    SVG_OUT.parent.mkdir(parents=True, exist_ok=True)
    SVG_OUT.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}">'
        f'<path fill="#0a0a0a" fill-rule="evenodd" d="{path_data}"/></svg>\n',
        encoding="utf-8",
    )


def write_ts(path_data: str, width: int, height: int) -> None:
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(
        f'''/**
 * The SUPARFLYYART "S" mark, traced from the master artwork as a single
 * closed polygon. Keeping it as path data (rather than a PNG) means it stays
 * razor-sharp at any size and can be drawn by Canvas, SVG, or Three.js alike.
 *
 * Generated by scripts/trace-logo.py — re-run that script instead of editing by hand.
 */
export const S_GLYPH = {{
  width: {width},
  height: {height},
  path: "{path_data}",
}} as const;

/** Width ÷ height of the mark — used to size glyph cells without distortion. */
export const S_GLYPH_ASPECT = S_GLYPH.width / S_GLYPH.height;
''',
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Trace the logo PNG into SVG + TypeScript path data.")
    parser.add_argument("image", type=Path, help="logo image, dark mark on a light background")
    parser.add_argument("--tolerance", type=float, default=2.5)
    parser.add_argument("--threshold", type=int, default=128)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    path_data, width, height, corners = trace(args.image, args.threshold, args.tolerance)
    print(f"Traced {corners} corners — mark is {width} x {height} px")

    if args.dry_run:
        print(path_data)
        return

    write_svg(path_data, width, height)
    write_ts(path_data, width, height)
    print(f"Wrote {SVG_OUT.relative_to(PROJECT_ROOT)}")
    print(f"Wrote {TS_OUT.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
